global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['host.docker.internal:8000']

#    metric_relabel_configs:
#      - source_labels: [handler]
#        regex: '/metrics'
#        action: drop